flowchart LR
  n_model__3_model_03_model_3_model_03["Model<br/>Model 3: model-03"]
  click n_model__3_model_03_model_3_model_03 "nodes/model--3-model-03-model-3-model-03/" "Open node folder"
  n_model__4_model_04_model_4_model_04["Model<br/>Model 4: model-04"]
  click n_model__4_model_04_model_4_model_04 "nodes/model--4-model-04-model-4-model-04/" "Open node folder"
  n_model__5_model_05_model_5_model_05["Model<br/>Model 5: model-05"]
  click n_model__5_model_05_model_5_model_05 "nodes/model--5-model-05-model-5-model-05/" "Open node folder"
  n_model__6_model_06_model_6_model_06["Model<br/>Model 6: model-06"]
  click n_model__6_model_06_model_6_model_06 "nodes/model--6-model-06-model-6-model-06/" "Open node folder"
  n_model__7_model_07_model_7_model_07["Model<br/>Model 7: model-07"]
  click n_model__7_model_07_model_7_model_07 "nodes/model--7-model-07-model-7-model-07/" "Open node folder"
  n_model__8_model_08_model_8_model_08["Model<br/>Model 8: model-08"]
  click n_model__8_model_08_model_8_model_08 "nodes/model--8-model-08-model-8-model-08/" "Open node folder"
  n_model__9_model_09_model_9_model_09["Model<br/>Model 9: model-09"]
  click n_model__9_model_09_model_9_model_09 "nodes/model--9-model-09-model-9-model-09/" "Open node folder"
  n_model__10_model_10_model_10_model_10["Model<br/>Model 10: model-10"]
  click n_model__10_model_10_model_10_model_10 "nodes/model--10-model-10-model-10-model-10/" "Open node folder"
  n_model__1_model_01_model_1_model_01["Model<br/>Model 1: model-01"]
  click n_model__1_model_01_model_1_model_01 "nodes/model--1-model-01-model-1-model-01/" "Open node folder"
  n_model__2_model_02_model_2_model_02["Model<br/>Model 2: model-02"]
  click n_model__2_model_02_model_2_model_02 "nodes/model--2-model-02-model-2-model-02/" "Open node folder"
  n_model__11_model_11_model_11_model_11["Model<br/>Model 11: model-11"]
  click n_model__11_model_11_model_11_model_11 "nodes/model--11-model-11-model-11-model-11/" "Open node folder"
  n_model__12_model_12_model_12_model_12["Model<br/>Model 12: model-12"]
  click n_model__12_model_12_model_12_model_12 "nodes/model--12-model-12-model-12-model-12/" "Open node folder"
  n_model__13_model_13_model_13_model_13["Model<br/>Model 13: model-13"]
  click n_model__13_model_13_model_13_model_13 "nodes/model--13-model-13-model-13-model-13/" "Open node folder"
  n_model__14_model_14_model_14_model_14["Model<br/>Model 14: model-14"]
  click n_model__14_model_14_model_14_model_14 "nodes/model--14-model-14-model-14-model-14/" "Open node folder"
  n_model__15_model_15_model_15_model_15["Model<br/>Model 15: model-15"]
  click n_model__15_model_15_model_15_model_15 "nodes/model--15-model-15-model-15-model-15/" "Open node folder"
  n_model__16_model_16_model_16_model_16["Model<br/>Model 16: model-16"]
  click n_model__16_model_16_model_16_model_16 "nodes/model--16-model-16-model-16-model-16/" "Open node folder"
  n_model__17_model_17_model_17_model_17["Model<br/>Model 17: model-17"]
  click n_model__17_model_17_model_17_model_17 "nodes/model--17-model-17-model-17-model-17/" "Open node folder"
  n_model__25_model_25_model_25_model_25["Model<br/>Model 25: model-25"]
  click n_model__25_model_25_model_25_model_25 "nodes/model--25-model-25-model-25-model-25/" "Open node folder"
  n_model__22_model_22_model_22_model_22["Model<br/>Model 22: model-22"]
  click n_model__22_model_22_model_22_model_22 "nodes/model--22-model-22-model-22-model-22/" "Open node folder"
  n_model__19_model_19_model_19_model_19["Model<br/>Model 19: model-19"]
  click n_model__19_model_19_model_19_model_19 "nodes/model--19-model-19-model-19-model-19/" "Open node folder"
  n_model__21_model_21_model_21_model_21["Model<br/>Model 21: model-21"]
  click n_model__21_model_21_model_21_model_21 "nodes/model--21-model-21-model-21-model-21/" "Open node folder"
  n_model__18_model_18_model_18_model_18["Model<br/>Model 18: model-18"]
  click n_model__18_model_18_model_18_model_18 "nodes/model--18-model-18-model-18-model-18/" "Open node folder"
  n_model__23_model_23_model_23_model_23["Model<br/>Model 23: model-23"]
  click n_model__23_model_23_model_23_model_23 "nodes/model--23-model-23-model-23-model-23/" "Open node folder"
  n_model__24_model_24_model_24_model_24["Model<br/>Model 24: model-24"]
  click n_model__24_model_24_model_24_model_24 "nodes/model--24-model-24-model-24-model-24/" "Open node folder"
  n_model__20_model_20_model_20_model_20["Model<br/>Model 20: model-20"]
  click n_model__20_model_20_model_20_model_20 "nodes/model--20-model-20-model-20-model-20/" "Open node folder"
  n_model__30_model_30_model_30_model_30["Model<br/>Model 30: model-30"]
  click n_model__30_model_30_model_30_model_30 "nodes/model--30-model-30-model-30-model-30/" "Open node folder"
  n_model__28_model_28_model_28_model_28["Model<br/>Model 28: model-28"]
  click n_model__28_model_28_model_28_model_28 "nodes/model--28-model-28-model-28-model-28/" "Open node folder"
  n_model__27_model_27_model_27_model_27["Model<br/>Model 27: model-27"]
  click n_model__27_model_27_model_27_model_27 "nodes/model--27-model-27-model-27-model-27/" "Open node folder"
  n_model__29_model_29_model_29_model_29["Model<br/>Model 29: model-29"]
  click n_model__29_model_29_model_29_model_29 "nodes/model--29-model-29-model-29-model-29/" "Open node folder"
  n_model__26_model_26_model_26_model_26["Model<br/>Model 26: model-26"]
  click n_model__26_model_26_model_26_model_26 "nodes/model--26-model-26-model-26-model-26/" "Open node folder"
  n_plot__1_plot_a_10_plot_bundle_a["Plot<br/>Plot bundle A"]
  click n_plot__1_plot_a_10_plot_bundle_a "nodes/plot--1-plot-a-10-plot-bundle-a/" "Open node folder"
  n_plot__2_plot_b_15_plot_bundle_b["Plot<br/>Plot bundle B"]
  click n_plot__2_plot_b_15_plot_bundle_b "nodes/plot--2-plot-b-15-plot-bundle-b/" "Open node folder"
  n_plot__11_plot_demo_default["Plot<br/>Plot demo default"]
  click n_plot__11_plot_demo_default "nodes/plot--11-plot-demo-default/" "Open node folder"
  n_plot__8_plot_demo_default["Plot<br/>Plot demo default"]
  click n_plot__8_plot_demo_default "nodes/plot--8-plot-demo-default/" "Open node folder"
  n_plot__3_plot_c_5_plot_bundle_c["Plot<br/>Plot bundle C"]
  click n_plot__3_plot_c_5_plot_bundle_c "nodes/plot--3-plot-c-5-plot-bundle-c/" "Open node folder"
  n_plot__13_plot_demo_default["Plot<br/>Plot demo default"]
  click n_plot__13_plot_demo_default "nodes/plot--13-plot-demo-default/" "Open node folder"
  n_plot__5_plot_demo_default["Plot<br/>Plot demo default"]
  click n_plot__5_plot_demo_default "nodes/plot--5-plot-demo-default/" "Open node folder"
  n_report__2_report_c_report_bundle_c["Report<br/>Report: bundle C"]
  click n_report__2_report_c_report_bundle_c "nodes/report--2-report-c-report-bundle-c/" "Open node folder"
  n_report__12_combined_report_default["Report<br/>Combined report default"]
  click n_report__12_combined_report_default "nodes/report--12-combined-report-default/" "Open node folder"
  n_report__4_combined_report_default["Report<br/>Combined report default"]
  click n_report__4_combined_report_default "nodes/report--4-combined-report-default/" "Open node folder"
  n_model__3_model_03_model_3_model_03 --> n_plot__1_plot_a_10_plot_bundle_a
  n_model__4_model_04_model_4_model_04 --> n_plot__1_plot_a_10_plot_bundle_a
  n_model__5_model_05_model_5_model_05 --> n_plot__1_plot_a_10_plot_bundle_a
  n_model__6_model_06_model_6_model_06 --> n_plot__1_plot_a_10_plot_bundle_a
  n_model__7_model_07_model_7_model_07 --> n_plot__1_plot_a_10_plot_bundle_a
  n_model__8_model_08_model_8_model_08 --> n_plot__1_plot_a_10_plot_bundle_a
  n_model__9_model_09_model_9_model_09 --> n_plot__1_plot_a_10_plot_bundle_a
  n_model__10_model_10_model_10_model_10 --> n_plot__1_plot_a_10_plot_bundle_a
  n_model__1_model_01_model_1_model_01 --> n_plot__1_plot_a_10_plot_bundle_a
  n_model__1_model_01_model_1_model_01 --> n_plot__11_plot_demo_default
  n_model__2_model_02_model_2_model_02 --> n_plot__1_plot_a_10_plot_bundle_a
  n_model__2_model_02_model_2_model_02 --> n_plot__11_plot_demo_default
  n_model__11_model_11_model_11_model_11 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__12_model_12_model_12_model_12 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__13_model_13_model_13_model_13 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__14_model_14_model_14_model_14 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__15_model_15_model_15_model_15 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__16_model_16_model_16_model_16 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__17_model_17_model_17_model_17 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__25_model_25_model_25_model_25 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__22_model_22_model_22_model_22 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__22_model_22_model_22_model_22 --> n_plot__11_plot_demo_default
  n_model__19_model_19_model_19_model_19 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__19_model_19_model_19_model_19 --> n_plot__8_plot_demo_default
  n_model__21_model_21_model_21_model_21 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__21_model_21_model_21_model_21 --> n_plot__11_plot_demo_default
  n_model__21_model_21_model_21_model_21 --> n_plot__8_plot_demo_default
  n_model__18_model_18_model_18_model_18 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__18_model_18_model_18_model_18 --> n_plot__8_plot_demo_default
  n_model__23_model_23_model_23_model_23 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__24_model_24_model_24_model_24 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__20_model_20_model_20_model_20 --> n_plot__2_plot_b_15_plot_bundle_b
  n_model__30_model_30_model_30_model_30 --> n_plot__3_plot_c_5_plot_bundle_c
  n_model__28_model_28_model_28_model_28 --> n_plot__11_plot_demo_default
  n_model__28_model_28_model_28_model_28 --> n_plot__3_plot_c_5_plot_bundle_c
  n_model__28_model_28_model_28_model_28 --> n_plot__13_plot_demo_default
  n_model__27_model_27_model_27_model_27 --> n_plot__3_plot_c_5_plot_bundle_c
  n_model__27_model_27_model_27_model_27 --> n_plot__13_plot_demo_default
  n_model__29_model_29_model_29_model_29 --> n_plot__3_plot_c_5_plot_bundle_c
  n_model__29_model_29_model_29_model_29 --> n_plot__13_plot_demo_default
  n_model__26_model_26_model_26_model_26 --> n_plot__3_plot_c_5_plot_bundle_c
  n_model__26_model_26_model_26_model_26 --> n_plot__13_plot_demo_default
  n_model__26_model_26_model_26_model_26 --> n_plot__5_plot_demo_default
  n_plot__3_plot_c_5_plot_bundle_c --> n_report__2_report_c_report_bundle_c
  n_plot__13_plot_demo_default --> n_report__12_combined_report_default
  n_plot__5_plot_demo_default --> n_report__4_combined_report_default

