flowchart LR
  n_model_01["Model<br/>Model 1: model-01"]
  click n_model_01 "nodes/model-01/" "Open node folder"
  n_model_02["Model<br/>Model 2: model-02"]
  click n_model_02 "nodes/model-02/" "Open node folder"
  n_model_03["Model<br/>Model 3: model-03"]
  click n_model_03 "nodes/model-03/" "Open node folder"
  n_model_04["Model<br/>Model 4: model-04"]
  click n_model_04 "nodes/model-04/" "Open node folder"
  n_model_05["Model<br/>Model 5: model-05"]
  click n_model_05 "nodes/model-05/" "Open node folder"
  n_model_06["Model<br/>Model 6: model-06"]
  click n_model_06 "nodes/model-06/" "Open node folder"
  n_model_07["Model<br/>Model 7: model-07"]
  click n_model_07 "nodes/model-07/" "Open node folder"
  n_model_08["Model<br/>Model 8: model-08"]
  click n_model_08 "nodes/model-08/" "Open node folder"
  n_model_09["Model<br/>Model 9: model-09"]
  click n_model_09 "nodes/model-09/" "Open node folder"
  n_model_10["Model<br/>Model 10: model-10"]
  click n_model_10 "nodes/model-10/" "Open node folder"
  n_model_11["Model<br/>Model 11: model-11"]
  click n_model_11 "nodes/model-11/" "Open node folder"
  n_model_12["Model<br/>Model 12: model-12"]
  click n_model_12 "nodes/model-12/" "Open node folder"
  n_model_13["Model<br/>Model 13: model-13"]
  click n_model_13 "nodes/model-13/" "Open node folder"
  n_model_14["Model<br/>Model 14: model-14"]
  click n_model_14 "nodes/model-14/" "Open node folder"
  n_model_15["Model<br/>Model 15: model-15"]
  click n_model_15 "nodes/model-15/" "Open node folder"
  n_model_16["Model<br/>Model 16: model-16"]
  click n_model_16 "nodes/model-16/" "Open node folder"
  n_model_17["Model<br/>Model 17: model-17"]
  click n_model_17 "nodes/model-17/" "Open node folder"
  n_model_18["Model<br/>Model 18: model-18"]
  click n_model_18 "nodes/model-18/" "Open node folder"
  n_model_19["Model<br/>Model 19: model-19"]
  click n_model_19 "nodes/model-19/" "Open node folder"
  n_model_20["Model<br/>Model 20: model-20"]
  click n_model_20 "nodes/model-20/" "Open node folder"
  n_model_21["Model<br/>Model 21: model-21"]
  click n_model_21 "nodes/model-21/" "Open node folder"
  n_model_22["Model<br/>Model 22: model-22"]
  click n_model_22 "nodes/model-22/" "Open node folder"
  n_model_23["Model<br/>Model 23: model-23"]
  click n_model_23 "nodes/model-23/" "Open node folder"
  n_model_24["Model<br/>Model 24: model-24"]
  click n_model_24 "nodes/model-24/" "Open node folder"
  n_model_25["Model<br/>Model 25: model-25"]
  click n_model_25 "nodes/model-25/" "Open node folder"
  n_model_26["Model<br/>Model 26: model-26"]
  click n_model_26 "nodes/model-26/" "Open node folder"
  n_model_27["Model<br/>Model 27: model-27"]
  click n_model_27 "nodes/model-27/" "Open node folder"
  n_model_28["Model<br/>Model 28: model-28"]
  click n_model_28 "nodes/model-28/" "Open node folder"
  n_model_29["Model<br/>Model 29: model-29"]
  click n_model_29 "nodes/model-29/" "Open node folder"
  n_model_30["Model<br/>Model 30: model-30"]
  click n_model_30 "nodes/model-30/" "Open node folder"
  n_plot_a_10["Plot<br/>Plot bundle A"]
  click n_plot_a_10 "nodes/plot-a-10/" "Open node folder"
  n_plot_b_15["Plot<br/>Plot bundle B"]
  click n_plot_b_15 "nodes/plot-b-15/" "Open node folder"
  n_plot_c_5["Plot<br/>Plot bundle C"]
  click n_plot_c_5 "nodes/plot-c-5/" "Open node folder"
  n_report_a_b["Report<br/>Report: bundles A+B"]
  click n_report_a_b "nodes/report-a-b/" "Open node folder"
  n_report_c["Report<br/>Report: bundle C"]
  click n_report_c "nodes/report-c/" "Open node folder"
  n_model_01 --> n_plot_a_10
  n_model_02 --> n_plot_a_10
  n_model_03 --> n_plot_a_10
  n_model_04 --> n_plot_a_10
  n_model_05 --> n_plot_a_10
  n_model_06 --> n_plot_a_10
  n_model_07 --> n_plot_a_10
  n_model_08 --> n_plot_a_10
  n_model_09 --> n_plot_a_10
  n_model_10 --> n_plot_a_10
  n_model_11 --> n_plot_b_15
  n_model_12 --> n_plot_b_15
  n_model_13 --> n_plot_b_15
  n_model_14 --> n_plot_b_15
  n_model_15 --> n_plot_b_15
  n_model_16 --> n_plot_b_15
  n_model_17 --> n_plot_b_15
  n_model_18 --> n_plot_b_15
  n_model_19 --> n_plot_b_15
  n_model_20 --> n_plot_b_15
  n_model_21 --> n_plot_b_15
  n_model_22 --> n_plot_b_15
  n_model_23 --> n_plot_b_15
  n_model_24 --> n_plot_b_15
  n_model_25 --> n_plot_b_15
  n_model_26 --> n_plot_c_5
  n_model_27 --> n_plot_c_5
  n_model_28 --> n_plot_c_5
  n_model_29 --> n_plot_c_5
  n_model_30 --> n_plot_c_5
  n_plot_a_10 --> n_report_a_b
  n_plot_b_15 --> n_report_a_b
  n_plot_c_5 --> n_report_c

